# Generated by Django 2.2.7 on 2019-12-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_auto_20191207_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrel',
            name='id',
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Unique_squirrel_ID',
            field=models.CharField(help_text='Unique squirrel id', max_length=50, primary_key=True, serialize=False),
        ),
    ]
