# Generated by Django 2.2.7 on 2019-11-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.DecimalField(decimal_places=2, help_text='Latitude of squirrel', max_digits=30)),
                ('Longitude', models.DecimalField(decimal_places=2, help_text='Longitude of squirrel', max_digits=30)),
                ('Unique_squirrel_ID', models.CharField(help_text='Unique squirrel id', max_length=50)),
                ('Hectare', models.CharField(help_text='Hectare of squirrel,like 32D', max_length=10)),
                ('Shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', help_text='Shift of squirrel', max_length=15)),
                ('Date', models.IntegerField(help_text='sighting session day and month')),
                ('Hectare_squirrel_num', models.SmallIntegerField(help_text='number within the chronological sequence of squirrel sightings')),
                ('Age', models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], default='Adult', help_text='Age of squirrel', max_length=15)),
                ('Primary_fur_color', models.CharField(choices=[('Gray', 'Gray'), ('Black', 'Black'), ('Cinnamon', 'Cinnamon')], default='Gray', help_text='Primary fur color of squirrel', max_length=20)),
                ('Location', models.CharField(choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], default='Ground Plane', help_text='location of squirrel', max_length=20)),
                ('Specific_location', models.CharField(help_text='Specific location of squirrel', max_length=100)),
                ('Running', models.BooleanField(help_text='run or not?')),
                ('Chasing', models.BooleanField(help_text='chase or not?')),
                ('Climbing', models.BooleanField(help_text='Climb or not?')),
                ('Eating', models.BooleanField(help_text='Eat or not?')),
                ('Foraging', models.BooleanField(help_text='Forage or not?')),
                ('Other_Activities', models.BooleanField(help_text='Does squirrel have other activities?')),
                ('Kuks', models.BooleanField(help_text='Kuks or not?')),
                ('Quaas', models.BooleanField(help_text='Quaas or not?')),
                ('Moans', models.BooleanField(help_text='Moans or not?')),
                ('Tail_flags', models.BooleanField(help_text='Tail flags or not?')),
                ('Tail_twitches', models.BooleanField(help_text='Tail twitches or not?')),
                ('Approaches', models.BooleanField(help_text='Approaches or not?')),
                ('Indifferent', models.BooleanField(help_text='Indifferent or not?')),
                ('Runs_from', models.BooleanField(help_text='Runs from or not?')),
            ],
        ),
    ]
