# Generated by Django 2.2.7 on 2019-12-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Date',
            field=models.CharField(help_text='sighting session day and month', max_length=10),
        ),
    ]
